CREATE DATABASE SmartHome

USE SmartHome

CREATE TABLE HOME (
  ID INT PRIMARY KEY NOT NULL,
  CODE VARCHAR(20) UNIQUE,
  NAME NVARCHAR(50),
  ADDRESS NVARCHAR(200),
  STATUS NVARCHAR(20),
  CREATE_AT DATETIME
)

CREATE TABLE USERS (
  ID INT PRIMARY KEY NOT NULL,
  USERNAME NVARCHAR(100),
  PASSWORD VARCHAR(100),
  FULL_NAME NVARCHAR(100),
  EMAIL NVARCHAR(100),
  ROLE NVARCHAR(50),
  CREATE_AT DATETIME
)

CREATE TABLE HOMEMODE (
  ID INT PRIMARY KEY NOT NULL,
  NAME NVARCHAR(100),
  ACTIVE_FROM TIME,
  ACTIVE_TO TIME,
  IS_ACTIVE BIT,
  HOME_ID INT,
  CONSTRAINT FK_HOME_MODE FOREIGN KEY (HOME_ID) REFERENCES HOME(ID)
)

CREATE TABLE ROOM (
  ID INT PRIMARY KEY NOT NULL,
  NAME NVARCHAR(100),
  FLOOR INT,
  TYPE NVARCHAR(50),
  STATUS NVARCHAR(20),
  HOME_ID INT,
  CONSTRAINT FK_HOME_ROOM FOREIGN KEY (HOME_ID) REFERENCES HOME(ID)
)

CREATE TABLE DEVICE (
  ID INT PRIMARY KEY NOT NULL,
  TYPE NVARCHAR(50),
  SERIAL_NO VARCHAR(50),
  VENDOR NVARCHAR(100),
  STATUS NVARCHAR(20),
  LAST_SEEN_ST DATETIME,
  ROOM_ID INT,
  CONSTRAINT FK_ROOM_DEVICE FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID)
)

CREATE TABLE ALERT (
  ID INT PRIMARY KEY NOT NULL,
   TYPE NVARCHAR(50),
   SEVERITY NVARCHAR(50),
   STATUS NVARCHAR(20),
   START_TS DATETIME,
   END_TS DATETIME,
   MESSAGE NVARCHAR(500),
   CREATE_AT DATETIME,
   USER_ID INT,
   HOME_ID INT,
   DEVICE_ID INT,
   ROOM_ID INT,
   CONSTRAINT FK_USER_ALERT FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
   CONSTRAINT FK_HOME_ALERT FOREIGN KEY (HOME_ID) REFERENCES HOME(ID),
   CONSTRAINT FK_DEVICE_ALERT FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID),
   CONSTRAINT FK_ROOM_ALERT FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
)

CREATE TABLE RULES (
  ID INT PRIMARY KEY NOT NULL,
  NAME NVARCHAR(100),
  TRIGGER_TYPE VARCHAR(50),
  CONDITION_JSON NVARCHAR(MAX),
  ACTION_JSON NVARCHAR(MAX),
  PRIORITY INT,
  ACTIVE BIT,
  CREATED_AT DATETIME,
  HOME_ID INT,
  ALERT_ID INT,
  CONSTRAINT FK_HOME_RULE FOREIGN KEY (HOME_ID) REFERENCES HOME(ID),
  CONSTRAINT FK_ALERT_RULE FOREIGN KEY (ALERT_ID) REFERENCES ALERT(ID),
)

CREATE TABLE EVENTLOG (
  ID INT PRIMARY KEY NOT NULL,
  TYPE NVARCHAR(20),
  VALUE VARCHAR(20),
  TS DATETIME,
  SOURCE VARCHAR(50),
  USER_ID INT,
  DEVICE_ID INT,
  CONSTRAINT FK_USER_LOG FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_DEVICE_LOG FOREIGN KEY (DEVICE_ID) REFERENCES DEVICE(ID)
)

CREATE TABLE ALERTACTION (
  ID INT PRIMARY KEY NOT NULL,
  TYPE NVARCHAR(20),
  NOTE NVARCHAR(MAX),
  ACTION_TS DATETIME,
  USER_ID INT,
  ALERT_ID INT,
  CONSTRAINT FK_USER_ACTION FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
  CONSTRAINT FK_ALERT_ACTION FOREIGN KEY (ALERT_ID) REFERENCES ALERT(ID)
)